### ISSUE TITLE
Why is this project without source code？

### ISSUE THREAD

**Issue by snikeguo** [microwan/spc5-hal#1]
I use SPC560B. I want to find a SPC5XXX library.

**Comment by snikeguo** [comment]
Are you an official from STMICROELECTRONICS？

**Comment by microwan** [comment]
Hello snikeguo ,

Yes,  The SPC5-HAL project implements an Hardware Abstraction Layer derived from the HAL of the ChibiOS/RT project.  It contains the driver for SPC560B family.

Download SPC5Studio for more informations (cf wiki and SPC5Studio Marketplace)
We have RLA (Register Level Access) drivers too.

        Best Regards

                          Erwan
